INSERT INTO tag_labels (value, category) VALUES ('1-General', 0);
INSERT INTO tag_labels (value, category) VALUES ('2-Clothing', 0);
INSERT INTO tag_labels (value, category) VALUES ('3-Furniture', 0);
INSERT INTO tag_labels (value, category) VALUES ('4-Grocery Taxable', 0);
INSERT INTO tag_labels (value, category) VALUES ('5-Shoes', 0);
INSERT INTO tag_labels (value, category) VALUES ('6-Fabric', 0);
INSERT INTO tag_labels (value, category) VALUES ('7-Flooring/Carpet', 0);
INSERT INTO tag_labels (value, category) VALUES ('8-Hardware', 0);
INSERT INTO tag_labels (value, category) VALUES ('9-Special Sales', 0);
INSERT INTO tag_labels (value, category) VALUES ('14-Grocery Non-Taxable', 0);
INSERT INTO tag_labels (value, category) VALUES ('Catalog Site Price', 1);
INSERT INTO tag_labels (value, category) VALUES ('Internet Site Price', 1);
INSERT INTO tag_labels (value, category) VALUES ('Office Store', 1);
INSERT INTO tag_labels (value, category) VALUES ('Big Box Price', 1);
INSERT INTO tag_labels (value, category) VALUES ('Drug Store Price', 1);
INSERT INTO tag_labels (value, category) VALUES ('Book Store Price', 1);
INSERT INTO tag_labels (value, category) VALUES ('Holiday Stock', 1);
INSERT INTO tag_labels (value, category) VALUES ('Supply Store Price', 1);
INSERT INTO tag_labels (value, category) VALUES ('Rug Store Price', 1);
INSERT INTO tag_labels (value, category) VALUES ('Garden Center Price', 1);
INSERT INTO tag_labels (value, category) VALUES ('Club Price', 1);
INSERT INTO tag_labels (value, category) VALUES ('Gift Shop Price', 1);
INSERT INTO tag_labels (value, category) VALUES ('Sporting Goods Store', 1);
INSERT INTO tag_labels (value, category) VALUES ('Mardens Price', 1);
INSERT INTO tag_labels (value, category) VALUES ('Retail Price', 1);
INSERT INTO tag_labels (value, category) VALUES ('Pet Shop Retail', 1);
INSERT INTO tag_labels (value, category) VALUES ('Dept Store Retail', 1);
INSERT INTO tag_labels (value, category) VALUES ('White', 2);
INSERT INTO tag_labels (value, category) VALUES ('Peach', 2);
INSERT INTO tag_labels (value, category) VALUES ('Rose', 2);
INSERT INTO tag_labels (value, category) VALUES ('Light-Purple', 2);
INSERT INTO tag_labels (value, category) VALUES ('Purple', 2);
INSERT INTO tag_labels (value, category) VALUES ('Dark-Purple', 2);
INSERT INTO tag_labels (value, category) VALUES ('Light-Blue', 2);
INSERT INTO tag_labels (value, category) VALUES ('Blue', 2);
INSERT INTO tag_labels (value, category) VALUES ('Dark-Blue', 2);
INSERT INTO tag_labels (value, category) VALUES ('Aqua', 2);
INSERT INTO tag_labels (value, category) VALUES ('Brown', 2);
INSERT INTO tag_labels (value, category) VALUES ('Dark-Brown', 2);
INSERT INTO tag_labels (value, category) VALUES ('Mint', 2);
INSERT INTO tag_labels (value, category) VALUES ('Green', 2);
INSERT INTO tag_labels (value, category) VALUES ('Dark-Green', 2);
INSERT INTO tag_labels (value, category) VALUES ('Yellow', 2);
INSERT INTO tag_labels (value, category) VALUES ('Dark-Yellow', 2);
INSERT INTO tag_labels (value, category) VALUES ('Light-Pink', 2);
INSERT INTO tag_labels (value, category) VALUES ('Pink', 2);
INSERT INTO tag_labels (value, category) VALUES ('Dark-Gray', 2);
INSERT INTO tag_labels (value, category) VALUES ('Teal', 2);
INSERT INTO tag_labels (value, category) VALUES ('Gray', 2);
INSERT INTO tag_labels (value, category) VALUES ('Colored (1in x 0.75in)', 3);
INSERT INTO tag_labels (value, category) VALUES ('Orange (0.8in x 0.5in)', 3);
INSERT INTO tag_labels (value, category) VALUES ('Large (1.25in x 1in)', 3);